# This is a basic workflow to help you get started with Actions

name: main s3 updater

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      # Runs a single command using the runners shell
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        run: npm install && npm run build
      - name: List Files
        run: ls dist/
      - name: Deploy to S3
        run: |
          aws s3 rm s3://hearbefore.nyc/ --recursive --exclude "*" --include "style.*" --include "hear-before.*" --include "modal.*" --include "worker.*"
          aws s3 sync ./dist/ s3://hearbefore.nyc/
          aws cloudfront create-invalidation --distribution-id E22B1PQX93ZS6S --paths "/index.html" "/modal.*" "/hear-before.*" "/style.*"

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.



